# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest #windows-latest

steps:
- task: UseNode@1
  inputs:
    version: '20.x'
- script: npm ci
  displayName: 'install Dependencies'
- script: npx playwright install --with-deps
  displayName: 'install Playwright Browsers'
- script: npx playwright test
  displayName: 'Execute Playwright Tests'
- task: PublishPipelineArtifact@1
  inputs:
    targetPath: 'playwright-report'
    artifact: 'Playwright HTML Report'
    publishLocation: 'pipeline'
  condition: always()